"""Initial migration.

Revision ID: 4957d3555cc8
Revises: 
Create Date: 2024-10-25 14:42:42.072695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4957d3555cc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordinates', sa.String(length=64), nullable=True),
    sa.Column('speed', sa.String(length=32), nullable=True),
    sa.Column('issue', sa.String(length=256), nullable=True),
    sa.Column('red_alert', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_query')
    op.drop_table('ocr_result')
    op.drop_table('alert')
    # ### end Alembic commands ###
